// 自动生成：名字与文件来自 hgplayer 1.1.6 bundle（captures/hgplayer-116-frontend.js 的
// h6/f6 表），图片为其中内联的 base64 webp，已落盘到 src/assets/emoji/。上游弹幕/评论文本以
// [名字] 代码携带表情，渲染时按本表换图。重新生成：从 bundle 重跑提取（提取脚本逻辑见提交记录）。
export const DANMAKU_EMOJI_FILES: readonly (readonly [name: string, file: string])[] = [
  ['[微笑]', 'e01.webp'],
  ['[偷笑]', 'e02.webp'],
  ['[笑]', 'e03.webp'],
  ['[什么]', 'e04.webp'],
  ['[害羞]', 'e05.webp'],
  ['[爱慕]', 'e06.webp'],
  ['[飞吻]', 'e07.webp'],
  ['[奸笑]', 'e08.webp'],
  ['[尬笑]', 'e09.webp'],
  ['[思考]', 'e10.webp'],
  ['[撇嘴]', 'e11.webp'],
  ['[做鬼脸]', 'e12.webp'],
  ['[酷]', 'e13.webp'],
  ['[翻白眼]', 'e14.webp'],
  ['[惊呆]', 'e15.webp'],
  ['[震惊]', 'e16.webp'],
  ['[送心]', 'e17.webp'],
  ['[委屈]', 'e18.webp'],
  ['[快哭了]', 'e19.webp'],
  ['[笑哭]', 'e20.webp'],
  ['[哭]', 'e21.webp'],
  ['[大笑]', 'e22.webp'],
  ['[舔屏]', 'e23.webp'],
  ['[怒]', 'e24.webp'],
  ['[捂脸]', 'e25.webp'],
  ['[吐]', 'e26.webp'],
  ['[恐惧]', 'e27.webp'],
  ['[抓狂]', 'e28.webp'],
  ['[敬礼]', 'e29.webp'],
  ['[石化]', 'e30.webp'],
  ['[OK]', 'e31.webp'],
  ['[赞]', 'e32.webp'],
  ['[爱心]', 'e33.webp'],
  ['[伤心]', 'e34.webp'],
  ['[KISS]', 'e35.webp'],
  ['[懂了]', 'e36.webp'],
  ['[探究]', 'e37.webp'],
  ['[重拳出击]', 'e38.webp'],
  ['[吃瓜]', 'e39.webp'],
  ['[盯]', 'e40.webp'],
  ['[你细品]', 'e41.webp'],
  ['[赶稿中]', 'e42.webp'],
  ['[注意]', 'e43.webp'],
  ['[饱了]', 'e44.webp'],
  ['[码住]', 'e45.webp'],
  ['[学会了]', 'e46.webp'],
  ['[顶帖]', 'e47.webp'],
  ['[求爆更]', 'e48.webp'],
  ['[求关注]', 'e49.webp'],
  ['[爽]', 'e50.webp'],
  ['[鼓掌]', 'e51.webp'],
  ['[没看够]', 'e52.webp'],
  ['[送花]', 'e53.webp'],
];
