/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as DetailRouteImport } from './routes/detail'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LikedRouteImport } from './routes/liked'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as NewRouteImport } from './routes/new'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as RankRouteImport } from './routes/rank'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailRoute = DetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LikedRoute = LikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/collections': typeof CollectionsRoute
  '/detail': typeof DetailRoute
  '/history': typeof HistoryRoute
  '/liked': typeof LikedRoute
  '/merge': typeof MergeRoute
  '/new': typeof NewRoute
  '/player': typeof PlayerRoute
  '/rank': typeof RankRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/collections': typeof CollectionsRoute
  '/detail': typeof DetailRoute
  '/history': typeof HistoryRoute
  '/liked': typeof LikedRoute
  '/merge': typeof MergeRoute
  '/new': typeof NewRoute
  '/player': typeof PlayerRoute
  '/rank': typeof RankRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/collections': typeof CollectionsRoute
  '/detail': typeof DetailRoute
  '/history': typeof HistoryRoute
  '/liked': typeof LikedRoute
  '/merge': typeof MergeRoute
  '/new': typeof NewRoute
  '/player': typeof PlayerRoute
  '/rank': typeof RankRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/collections'
    | '/detail'
    | '/history'
    | '/liked'
    | '/merge'
    | '/new'
    | '/player'
    | '/rank'
    | '/reservations'
    | '/settings'
    | '/storage'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/collections'
    | '/detail'
    | '/history'
    | '/liked'
    | '/merge'
    | '/new'
    | '/player'
    | '/rank'
    | '/reservations'
    | '/settings'
    | '/storage'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/collections'
    | '/detail'
    | '/history'
    | '/liked'
    | '/merge'
    | '/new'
    | '/player'
    | '/rank'
    | '/reservations'
    | '/settings'
    | '/storage'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CollectionsRoute: typeof CollectionsRoute
  DetailRoute: typeof DetailRoute
  HistoryRoute: typeof HistoryRoute
  LikedRoute: typeof LikedRoute
  MergeRoute: typeof MergeRoute
  NewRoute: typeof NewRoute
  PlayerRoute: typeof PlayerRoute
  RankRoute: typeof RankRoute
  ReservationsRoute: typeof ReservationsRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail': {
      id: '/detail'
      path: '/detail'
      fullPath: '/detail'
      preLoaderRoute: typeof DetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liked': {
      id: '/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof LikedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CollectionsRoute: CollectionsRoute,
  DetailRoute: DetailRoute,
  HistoryRoute: HistoryRoute,
  LikedRoute: LikedRoute,
  MergeRoute: MergeRoute,
  NewRoute: NewRoute,
  PlayerRoute: PlayerRoute,
  RankRoute: RankRoute,
  ReservationsRoute: ReservationsRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
